# espanso match file

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

# @see: https://espanso.org/docs/

matches:
  - trigger: ";cl"
    replace: "console.log($|$);"

  - trigger: ";cc"
    replace: "Claude Code"

  - trigger: ";js"
    replace: "```js\n$|$\n```"

  - trigger: ";;."
    replace: "…"

  # Placeholders
  ## Click
  - trigger: ";;c"
    replace: "{{% $|$ %}}"

  ## Type
  - trigger: ";;t"
    replace: "{{_ $|$ _}}"

  ## Select
  - trigger: ";;s"
    replace: "{{#\n- [ ] $|$\n#}}"

  ## Do
  - trigger: ";;d"
    replace: "{{$\n$|$\n$}}"

  # Common
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ";time"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%H:%M:%S"

  ## Arrow keys
  - trigger: ";;j"
    replace: "←"

  - trigger: ";;k"
    replace: "↓"

  - trigger: ";;l"
    replace: "→"

  - trigger: ";;i"
    replace: "↑"

  # - trigger: ";link"
  #  replace: "[{{clipboard}}]($|$)"
  #  vars:
  #    - name: clipboard
  #      type: clipboard

  # Print the output of a shell command
  - trigger: ";shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"
