onboarding = false

[theme]
name = "catppuccin-latte"
auto_switch = false

[keys]
prefix = "cmd+;"

switch_tab = "cmd+1..9"
new_tab = "cmd+t"
next_tab = "cmd+shift+right"
previous_tab = "cmd+shift+left"

split_vertical = "cmd+d"
split_horizontal = "cmd+shift+d"
focus_pane_left = "cmd+j"
focus_pane_up = "cmd+i"
focus_pane_right = "cmd+l"
focus_pane_down = "cmd+k"

detach = "prefix+q"

[ui.toast]
delivery = "herdr"

[ui]
show_agent_labels_on_pane_borders = true
