onboarding = false

[theme]
name = "catppuccin-latte"
auto_switch = false

[keys]
prefix = "cmd+;"

switch_tab = "cmd+1..9"
new_tab = "cmd+t"
next_tab = "cmd+alt+right"
previous_tab = "cmd+alt+left"

split_vertical = "cmd+d"
split_horizontal = "cmd+shift+d"
focus_pane_left = "cmd+j"
focus_pane_up = "cmd+i"
focus_pane_right = "cmd+l"
focus_pane_down = "cmd+k"

next_workspace = "ctrl+alt+down"
previous_workspace = "ctrl+alt+up"
next_agent = "cmd+]"
previous_agent = "cmd+["

new_workspace = "cmd+shift+n"
new_worktree = "cmd+n"

detach = "prefix+q"

[ui.toast]
delivery = "herdr"

[ui]
show_agent_labels_on_pane_borders = true
